# Default values for ngrok.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: netmanito/ngrok
  tag: armhfs
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4040

expose:
  service: grafana:3000

token: 1QPgCdpjymMBTgS3Z4Nh0L6442H_Ycx3Ln4qbSEjtyFZWDpP

nodeSelector: {}

tolerations: []

affinity: {}

subdomain:
